site_name: Slist Documentation
site_description: Documentation for the Slist Python package - a typesafe list with more method chaining!
site_url: https://thejaminator.github.io/slist/
repo_url: https://github.com/thejaminator/slist
repo_name: thejaminator/slist

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [slist]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_bases: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference:
    - Slist: api/slist.md
  - Contributing: contributing.md 