site_name: Slist Documentation
site_description: Documentation for the Slist Python package - a typesafe list with more method chaining!
site_url: https://thejaminator.github.io/slist/
repo_url: https://github.com/thejaminator/slist
repo_name: thejaminator/slist

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [slist]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_bases: true
            heading_level: 2
            members_order: source
            show_if_no_docstring: true
            separate_signature: true
            docstring_section_style: table
            show_root_toc_entry: true
            show_root_members_full_path: false
            docstring_options:
              ignore_init_summary: true
              # hide_parameters: true
              # hide_returns: true
              # hide_examples: true
            members_order: source
            show_signature_annotations: true
            signature_crossrefs: true
            filters: ["!^_"]
            docstring_style: google
            show_docstring_attributes: true
            show_docstring_examples: false
            show_docstring_returns: false
            show_docstring_parameters: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
      baselevel: 1

nav:
  - Home: index.md
  - Slist: api/slist.md
  - Contributing: contributing.md 