name: docs
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'slist/**'
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install poetry
      - run: poetry install -E doc
      - run: pip install mkdocs-material mkdocs mkdocstrings[python]
      - run: pip install -e .
      - name: Build and Deploy Documentation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          poetry run mkdocs build --verbose
          poetry run mkdocs gh-deploy --force --verbose 